# Generated by Django 5.0.6 on 2024-08-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('cert', models.TextField()),
                ('start_date', models.IntegerField(max_length=10)),
                ('end_date', models.IntegerField(default=True, max_length=10)),
            ],
        ),
    ]
