# Generated by Django 5.0.6 on 2024-08-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.IntegerField(),
        ),
    ]
