# Generated by Django 5.0.6 on 2024-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0003_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(blank=True, upload_to='static/gallery_images')),
                ('img_name', models.TextField()),
                ('img_desc', models.TextField()),
                ('img_category', models.CharField(choices=[('Website', 'Website'), ('Graphics', 'Graphics')], max_length=10)),
                ('img_link', models.TextField(blank=True)),
            ],
        ),
    ]
