# Generated by Django 5.0.6 on 2024-08-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0004_image_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_gallery',
            name='main_img',
            field=models.ImageField(upload_to='static/gallery_images'),
        ),
    ]
