# Generated by Django 5.0.6 on 2025-01-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0006_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_gallery',
            name='img_name',
        ),
        migrations.AlterField(
            model_name='about',
            name='my_img',
            field=models.ImageField(blank=True, upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='image_gallery',
            name='main_img',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
    ]
