# Generated by Django 5.0.6 on 2025-01-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0007_remove_image_gallery_img_name_alter_about_my_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_gallery',
            name='img_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
