# Generated by Django 5.0.6 on 2025-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0009_about_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_gallery',
            name='img_name',
            field=models.TextField(blank=True),
        ),
    ]
