# Generated by Django 5.0.6 on 2025-01-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0010_alter_image_gallery_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Insta_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='git_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='wa_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='x_link',
            field=models.TextField(blank=True),
        ),
    ]
