# Generated by Django 5.0.6 on 2025-01-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0011_about_insta_link_about_email_about_git_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Insta_link',
            new_name='insta_link',
        ),
    ]
