# Generated by Django 5.1.4 on 2025-01-12 13:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0012_rename_insta_link_about_insta_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('img_name', models.TextField(blank=True)),
                ('img_desc', models.TextField()),
                ('img_category', models.CharField(choices=[('Website', 'Website'), ('Graphics', 'Graphics')], max_length=10)),
                ('img_link', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='new_message',
            new_name='NewMessage',
        ),
        migrations.DeleteModel(
            name='image_gallery',
        ),
        migrations.AlterField(
            model_name='about',
            name='my_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
