# Generated by Django 5.1.4 on 2025-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0014_about_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.TextField(),
        ),
    ]
