# Generated by Django 5.1.4 on 2025-01-12 19:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayokunnu', '0015_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='my_cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
